version: '3'
services:
  application:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - .:/app
    ports:
      - "8000:3000"