FROM node:8.12.0-alpine

WORKDIR '/app'

# Install dependencies
COPY package.json .
RUN npm install

# Copy the code
COPY . .

# Build the project
RUN npm run build

# Tell docker what to run as default
CMD ["npm", "run", "dev"]